### ISSUE TITLE
Issue with os.path.expandvars and odd filenames

### ISSUE THREAD

**Issue by daniels1996** [kubinka0505/filedate#2]
I stumbled upon this pretty recently, and thought to make a post to see if it was something the maintainers were interested in.

When instantiating a File class, if the file path has the substring "$$" somewhere in the path, it will be scrubbed by the __init__ function for File due to os.path.expandvars. 

Example:
Original path: "X:\TestFolder\TestSubFolder\check_request$$fromjim.pdf"
self.file in the class post initialization: Original path: "X:\TestFolder\TestSubFolder\check_request$fromjim.pdf"

I know this is probably a ridiculous edge case but technically "$$" is allowed in Windows for a document name so it will cause the file to not be found by the library.

This can be worked around by overriding the "file" property on the class in my testing.

Thanks!

**Comment by kubinka0505** [comment]
Would this code implementation be a solution? This would clone each character in `characters` variable in each path component splitted by system path separator.

```python
characters = ["$"]

path = path.split(os.sep)
for elem in path:
    for character in path:
        path[path.index(elem)] = elem.replace(character * 2)

path = os.path.join(*path)
```

**Comment by kubinka0505** [comment]
New update will abandon the `os.path.expandvars` function, leaving all of the files path management to user

**Comment by kubinka0505** [comment]
Please reopen if problem will still occur
