### ISSUE TITLE
Add possibility to use it in folders

### ISSUE THREAD

**Issue by IlluminatiWave** [kubinka0505/filedate#3]
Trying to use it in folders (windows), it produces a strange behavior, the "details" view shows the date correctly, but in properties it shows the actual date of creation of the folder.

**Comment by kubinka0505** [comment]
Have you tried to refresh the file explorer (<kbd>F5</kbd>) and then check again?

**Comment by IlluminatiWave** [comment]
> refresh the file explorer

I mentioned it, windows explorer is not the problem. (modified date column)

> the "details" view shows the date correctly

Where it is not displayed correctly is when parsing it in properties (right click > folder properties).
The creation date is preserved even if it is manually modified (File_Date.set(...) )

**Comment by kubinka0505** [comment]
Fix was made and will be introduced in the next update
